### ISSUE TITLE
 Khởi tạo Appota SDK4 bị lỗi NullPointerException

### ISSUE THREAD

**Issue by soibat** [appota/android-game-sdk#1]
Khi debug đến dòng 46:
AppotaGameSDK.getInstance().setHideWelcomeView(false)
                .autoCatchException().setKeepLoginSession(true)
                .setSDKButtonVisibility(true).setAutoShowLoginDialog(false)
                .configure(this, new MyImplApptaGameSDKCallback());
bị lỗi java.lang.NullPointerException

My Logcat:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.silverwolf.appotademo/com.silverwolf.appotademo.MainActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2205)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
            at android.app.ActivityThread.access$800(ActivityThread.java:142)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5118)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at com.appota.gamesdk.v4.core.AppotaGameSDK.o(AppotaGameSDK.java:721)
            at com.appota.gamesdk.v4.core.AppotaGameSDK.configure(AppotaGameSDK.java:253)
            at com.silverwolf.appotademo.MainActivity.onCreate(MainActivity.java:46)

Ai biết cách khắc phục, vui lòng chỉ mình giúp. Xin cảm ơn

**Comment by n2a5me** [comment]
Chào bạn, bạn xem đã khai báo thẻ meta-data <meta-data android:name="com.appota.apiKey" android:value="your_appota_api_key" /> chưa?
Đồng thời bạn cần phải cung cấp đầy đủ những quyền cơ bản của SDK, những quyền nâng cao khác thì tùy tính năng bạn xử dụng.

**Comment by soibat** [comment]
Cảm ơn bạn đã trả lời.
Mình đã cung cấp đầy đủ tất cả các quyền và các thẻ meta nhưng trong hướng dẫn. Đây là file Manifest của mình:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.silverwolf.appotademo" >

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.USE_CREDENTIALS" />
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />
    <uses-permission android:name="com.android.vending.BILLING" />

    <meta-data android:name="com.appota.apiKey" android:value="K-A175597-U00000-JI80LJ-B16099AE7AD51E40" />
    <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/your_facebook_app_id" />
    <meta-data android:name="com.appota.twitter.consumer.key" android:value="@string/your_twitter_consumer_key" />
    <meta-data android:name="com.appota.twitter.consumer.secret" android:value="@string/your_twitter_consumer_secret" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity
            android:name="com.appota.gamesdk.v4.ui.BaseSDKActivty"
            android:configChanges="screenSize|orientation|keyboardHidden"
            android:theme="@android:style/Theme.Dialog" >
        </activity>
        <activity
            android:name="com.appota.facebook.LoginActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" />

    </application>

**Comment by n2a5me** [comment]
Chào bạn :-D, 
Thẻ meta-data khai báo trong thẻ application bạn nhé :-D.
Bạn cũng nên thêm quyền READ_PHONE_STATE, để cung cấp thông tin device khi SDK catch exception bạn nhé.

**Comment by soibat** [comment]
Mình đã fix được, cảm ơn bạn đã support. :)
